version: '3.8'

services:
  backend:
    image: 'backend:latest'
    build: .
    depends_on:
      - theboys-db
    environment:
      - POSTGRES_URL=jdbc:postgresql://theboys-db:5432/theboys
      - POSTGRES_USERNAME=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "8080:8080"

  theboys-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: theboys
    ports:
      - "5432:5432"
