alter table if exists theboys.candidate_requests drop constraint if exists FK6p18ycejl4iqnp7me3neqw3xo;
alter table if exists theboys.hero_creation_events drop constraint if exists FKp96ch72xasoo0dep874c2y5cx;
alter table if exists theboys.hero_creation_events drop constraint if exists FKnq8b6sy1w3bavuh1cr3beeer9;
alter table if exists theboys.hero_creation_orders drop constraint if exists FK3a2563eo2bu85j2gy7ncsve48;
alter table if exists theboys.heroes_skills drop constraint if exists FKfb86n50ehxp2jpxbw56w95ap0;
alter table if exists theboys.heroes_skills drop constraint if exists FKr2toc6rbynlu9wwbvy889rvmi;
alter table if exists theboys.orders drop constraint if exists FKpxtb8awmi0dk6smoh2vp1litg;
alter table if exists theboys.orders drop constraint if exists FKp69uui117r5ncrp0phuo05vwk;
alter table if exists theboys.orders_skills drop constraint if exists FKqm4qlmra4c1xj15llg1qmwtg8;
alter table if exists theboys.orders_skills drop constraint if exists FK9c5ybtl5jgnlf5hv2u4pjvrnq;
alter table if exists theboys.researches drop constraint if exists FKree188qn5e0xgjitvgc5qq9em;
alter table if exists theboys.user_hero_subscriptions drop constraint if exists FK8y3y007qm6l4ycwleu7gx5bdr;
alter table if exists theboys.user_hero_subscriptions drop constraint if exists FKcd7pox5echlro704ncyny10ap;
drop table if exists theboys.candidate_requests cascade;
drop table if exists theboys.candidates cascade;
drop table if exists theboys.customers cascade;
drop table if exists theboys.hero_creation_events cascade;
drop table if exists theboys.hero_creation_orders cascade;
drop table if exists theboys.heroes cascade;
drop table if exists theboys.heroes_skills cascade;
drop table if exists theboys.managers cascade;
drop table if exists theboys.orders cascade;
drop table if exists theboys.orders_skills cascade;
drop table if exists theboys.posts cascade;
drop table if exists theboys.researches cascade;
drop table if exists theboys.scientists cascade;
drop table if exists theboys.skills cascade;
drop table if exists theboys.user_hero_subscriptions cascade;
drop table if exists theboys.users cascade;
drop sequence if exists customers_seq;
drop sequence if exists candidates_seq;
drop sequence if exists heroes_seq;
drop sequence if exists orders_seq;
drop sequence if exists posts_seq;
drop sequence if exists researches_seq;
drop sequence if exists skills_seq;
drop sequence if exists users_seq;
create schema if not exists theboys;
create table theboys.candidate_requests (birthday date not null, candidate_order_id integer not null, height integer not null, scientist_id integer, weight integer not null, description varchar(255), race varchar(255), sex varchar(255), primary key (candidate_order_id));
create table theboys.candidates (birthday date not null, candidate_id integer not null, height integer not null, weight integer not null, address varchar(255), description varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, phone varchar(255), race varchar(255), sex varchar(255), medical_doc bytea, photo bytea, status varchar(255) not null check (status in ('IN_PROGRESS', 'WAITING')), primary key (candidate_id));
create table theboys.customers (customer_id integer not null, primary key (customer_id));
create table theboys.hero_creation_events (candidate_id integer, date date not null, hero_creation_event_id integer not null, scientist_id integer, result varchar(255) not null, primary key (hero_creation_event_id));
create table theboys.hero_creation_orders (hero_creation_order_id integer not null, manager_id integer, primary key (hero_creation_order_id));
create table theboys.heroes (hero_id integer not null, description varchar(255), name varchar(255) not null unique, primary key (hero_id));
create table theboys.heroes_skills (hero_id integer not null, skill_id integer not null, primary key (hero_id, skill_id));
create table theboys.managers (manager_id integer not null, primary key (manager_id));
create table theboys.orders (cost integer, customer_id integer not null, date date, hero_id integer, order_id integer not null, hero_description varchar(255), status varchar(255) not null check (status in ('PENDING','IN_PROGRESS','WAITING_FOR_CUSTOMER_APPROVAL','FULFILLED','DECLINED')), primary key (order_id));
create table theboys.orders_skills (order_id integer not null, skill_id integer not null, primary key (order_id, skill_id));
create table theboys.posts (hero_id integer not null, post_id integer not null, description varchar(255), title varchar(255) not null, primary key (post_id));
create table theboys.scientists (scientist_id integer not null, primary key (scientist_id));
create table theboys.skills (skill_id integer not null, description varchar(255), name varchar(255) not null unique, primary key (skill_id));
create table theboys.user_hero_subscriptions (hero_id integer not null, user_id integer not null);
create table theboys.users (id integer not null, login varchar(255) not null unique, password varchar(255) not null, role varchar(255) not null check (role in ('VISITOR','SCIENTIST','MANAGER','HERO','CANDIDATE','CUSTOMER')), primary key (id));
create table theboys.researches (research_id integer not null, scientist_id integer, result varchar(255), primary key (research_id));
create sequence customers_seq start with 1 increment by 50;
create sequence candidates_seq start with 1 increment by 50;
create sequence heroes_seq start with 1 increment by 50;
create sequence orders_seq start with 1 increment by 50;
create sequence posts_seq start with 1 increment by 50;
create sequence researches_seq start with 1 increment by 50;
create sequence skills_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;
alter table if exists theboys.candidate_requests add constraint FK6p18ycejl4iqnp7me3neqw3xo foreign key (scientist_id) references theboys.scientists;
alter table if exists theboys.hero_creation_events add constraint FKp96ch72xasoo0dep874c2y5cx foreign key (candidate_id) references theboys.candidates;
alter table if exists theboys.hero_creation_events add constraint FKnq8b6sy1w3bavuh1cr3beeer9 foreign key (scientist_id) references theboys.scientists;
alter table if exists theboys.hero_creation_orders add constraint FK3a2563eo2bu85j2gy7ncsve48 foreign key (manager_id) references theboys.managers;
alter table if exists theboys.heroes_skills add constraint FKfb86n50ehxp2jpxbw56w95ap0 foreign key (skill_id) references theboys.skills;
alter table if exists theboys.heroes_skills add constraint FKr2toc6rbynlu9wwbvy889rvmi foreign key (hero_id) references theboys.heroes;
alter table if exists theboys.orders add constraint FKpxtb8awmi0dk6smoh2vp1litg foreign key (customer_id) references theboys.customers;
alter table if exists theboys.orders add constraint FKp69uui117r5ncrp0phuo05vwk foreign key (hero_id) references theboys.heroes;
alter table if exists theboys.orders_skills add constraint FKqm4qlmra4c1xj15llg1qmwtg8 foreign key (skill_id) references theboys.skills;
alter table if exists theboys.orders_skills add constraint FK9c5ybtl5jgnlf5hv2u4pjvrnq foreign key (order_id) references theboys.hero_creation_orders;
alter table if exists theboys.researches add constraint FKree188qn5e0xgjitvgc5qq9em foreign key (scientist_id) references theboys.scientists;
alter table if exists theboys.user_hero_subscriptions add constraint FK8y3y007qm6l4ycwleu7gx5bdr foreign key (hero_id) references theboys.heroes;
alter table if exists theboys.user_hero_subscriptions add constraint FKcd7pox5echlro704ncyny10ap foreign key (user_id) references theboys.users;

